relative_permalinks: false
include: ['.htaccess']
exclude: ['node_modules', 'scss', 'Gruntfile.js', 'package.json', '*.sublime-project', '*.sublime-workspace','bower_components']
timezone: Europe/London

paginate: 8
paginate_path: /page:num

encoding: "utf-8"

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems: ['jekyll-paginate']
